### ISSUE TITLE
Add video page hangs when adding movie with duplicate name.

### ISSUE THREAD

**Issue by acmattson3** [mbaran3/CS372_Webpage#13]
When adding a movie with a duplicate name, the add movie page loads forever, and the console prints:
```
{ name: 'Title', discription: 'desc', link: false }
[
  {
    name: 'Title',
    discription: 'desc',
    link: 'false',
    likes: [],
    views: 0,
    comment: [],
    _id: new ObjectId('662a9c962103b3f37070107e'),
    __v: 0
  }
]
desc
{ name: 'Title', discription: 'desc', link: false }
error adding content
```

**Comment by mbaran3** [comment]
you now receive an error message telling you that the video name is already taken

**Comment by acmattson3** [comment]
New dockerized server now crashes when renaming a movie with the same name. Below is the lengthy error message:
```
cs372_webpage-mongodb-1  | {"t":{"$date":"2024-04-26T23:45:41.503+00:00"},"s":"W",  "c":"WRITE",    "id":7267501, "ctx":"conn3","msg":"Plan executor error during findAndModify","attr":{"error":{"code":11000,"codeName":"DuplicateKey","errmsg":"E11000 duplicate key error collection: test.contents index: name_1 dup key: { name: \"Woof\" }","keyPattern":{"name":1},"keyValue":{"name":"Woof"}},"stats":{"stage":"UPDATE","nReturned":0,"executionTimeMillisEstimate":0,"works":1,"advanced":0,"needTime":0,"needYield":0,"saveState":0,"restoreState":0,"failed":true,"isEOF":0,"nMatched":0,"nWouldModify":0,"nWouldUpsert":0,"inputStage":{"stage":"FETCH","nReturned":1,"executionTimeMillisEstimate":0,"works":1,"advanced":1,"needTime":0,"needYield":0,"saveState":1,"restoreState":0,"isEOF":0,"docsExamined":1,"alreadyHasObj":0,"inputStage":{"stage":"IXSCAN","nReturned":1,"executionTimeMillisEstimate":0,"works":1,"advanced":1,"needTime":0,"needYield":0,"saveState":1,"restoreState":0,"isEOF":0,"keyPattern":{"name":1},"indexName":"name_1","isMultiKey":false,"multiKeyPaths":{"name":[]},"isUnique":true,"isSparse":false,"isPartial":false,"indexVersion":2,"direction":"forward","indexBounds":{"name":["[\"E\", \"E\"]"]},"keysExamined":1,"seeks":1,"dupsTested":0,"dupsDropped":0}}}}}
cs372_webpage-webpage-1  | /node_modules/mongodb/lib/cmap/connection.js:281
cs372_webpage-webpage-1  |                     throw new error_1.MongoServerError(document);
cs372_webpage-webpage-1  |                           ^
cs372_webpage-webpage-1  |
cs372_webpage-webpage-1  | MongoServerError: Plan executor error during findAndModify :: caused by :: E11000 duplicate key error collection: test.contents index: name_1 dup key: { name: "Woof" }
cs372_webpage-webpage-1  |     at Connection.sendCommand (/node_modules/mongodb/lib/cmap/connection.js:281:27)
cs372_webpage-webpage-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
cs372_webpage-webpage-1  |     at async Connection.command (/node_modules/mongodb/lib/cmap/connection.js:304:26)
cs372_webpage-webpage-1  |     at async Server.command (/node_modules/mongodb/lib/sdam/server.js:169:24)
cs372_webpage-webpage-1  |     at async FindOneAndUpdateOperation.execute (/node_modules/mongodb/lib/operations/find_and_modify.js:91:24)
cs372_webpage-webpage-1  |     at async executeOperation (/node_modules/mongodb/lib/operations/execute_operation.js:126:16)
cs372_webpage-webpage-1  |     at async model.Query._findOneAndUpdate (/node_modules/mongoose/lib/query.js:3337:13)
cs372_webpage-webpage-1  |     at async model.Query.exec (/node_modules/mongoose/lib/query.js:4330:63)
cs372_webpage-webpage-1  |     at async /src/server.js:85:23 {
cs372_webpage-webpage-1  |   errorResponse: {
cs372_webpage-webpage-1  |     ok: 0,
cs372_webpage-webpage-1  |     errmsg: 'Plan executor error during findAndModify :: caused by :: E11000 duplicate key error collection: test.contents index: name_1 dup key: { name: "Woof" }',
cs372_webpage-webpage-1  |     code: 11000,
cs372_webpage-webpage-1  |     codeName: 'DuplicateKey',
cs372_webpage-webpage-1  |     keyPattern: { name: 1 },
cs372_webpage-webpage-1  |     keyValue: { name: 'Woof' }
cs372_webpage-webpage-1  |   },
cs372_webpage-webpage-1  |   ok: 0,
cs372_webpage-webpage-1  |   code: 11000,
cs372_webpage-webpage-1  |   codeName: 'DuplicateKey',
cs372_webpage-webpage-1  |   keyPattern: { name: 1 },
cs372_webpage-webpage-1  |   keyValue: { name: 'Woof' },
cs372_webpage-webpage-1  |   [Symbol(errorLabels)]: Set(0) {}
cs372_webpage-webpage-1  | }
cs372_webpage-webpage-1  |
cs372_webpage-webpage-1  | Node.js v22.0.0
cs372_webpage-mongodb-1  | {"t":{"$date":"2024-04-26T23:45:41.520+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn1","msg":"Interrupted operation as its client disconnected","attr":{"opId":10741}}
cs372_webpage-mongodb-1  | {"t":{"$date":"2024-04-26T23:45:41.523+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"172.19.0.3:37376","uuid":{"uuid":{"$uuid":"ea0ba5ab-d6d8-4cbb-9d01-e4327ccdfbd9"}},"connectionId":1,"connectionCount":3}}
cs372_webpage-mongodb-1  | {"t":{"$date":"2024-04-26T23:45:41.523+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"172.19.0.3:37386","uuid":{"uuid":{"$uuid":"b60c9f6f-c58a-4505-a95e-fc9b261554eb"}},"connectionId":2,"connectionCount":2}}
cs372_webpage-mongodb-1  | {"t":{"$date":"2024-04-26T23:45:41.523+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn4","msg":"Connection ended","attr":{"remote":"172.19.0.3:57644","uuid":{"uuid":{"$uuid":"cde3f39b-fd96-4358-9029-a669951d13ce"}},"connectionId":4,"connectionCount":1}}
cs372_webpage-mongodb-1  | {"t":{"$date":"2024-04-26T23:45:41.523+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn3","msg":"Connection ended","attr":{"remote":"172.19.0.3:37392","uuid":{"uuid":{"$uuid":"9cfb5517-3cd0-4f0d-a24a-5d1cdf877770"}},"connectionId":3,"connectionCount":0}}
cs372_webpage-webpage-1 exited with code 1
```
